### ISSUE TITLE
Validate that the data has been stored properly (non-null) in ComputeEngine.java (receiveComputeRequest)

### ISSUE THREAD

**Issue by dgunther2001** [dgunther2001/Software_Engineering_2024#47]

**Comment by Nikolas023** [comment]
Exception handled in lines 15-17. Added another condition to check if the number of rectangles is null.
if (data.getRectangles() <= 0 || data.getRectangles() == null)
    		throw new IllegalArgumentException("Num args have to be > 0");
    	}
