### ISSUE TITLE
Validate data exists and is non-null in DataStore.java (receiveDataStoreRequest)

### ISSUE THREAD

**Issue by dgunther2001** [dgunther2001/Software_Engineering_2024#48]

**Comment by Nikolas023** [comment]
Added a conditional statement to catch if the list of data is empty in newData: 
public void receiveDataStoreRequest(ProtoDataStream newData) throws Exception {
		if(newData.getData().equals(null)) {
			throw new Exception("Data cannot be null");
		} 
		data.append(newData);
	}
